/*
 * This file is generated by jOOQ.
 */
package com.example.demodb.entityUpdate;


import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;



@Entity
@Data
@AllArgsConstructor
@NoArgsConstructor
public class Appversions {
    @Id
    private String VERSION;
}
