/*
 * This file is generated by jOOQ.
 */
package com.example.demodb.entityUpdate;


import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;


import java.util.UUID;

@Entity
@Data
@AllArgsConstructor
@NoArgsConstructor
public class City {

    @Id
    private UUID CITYID;
    private String NAME;
    private String LON;
    private String LAT;
}
