/*
 * This file is generated by jOOQ.
 */
package com.example.demodb.entityUpdate;


import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.Cascade;
import org.hibernate.annotations.CascadeType;

import java.util.ArrayList;
import java.util.UUID;


/*
* VINCOLI NON AGGIUNTI:
* unique(relativeid, accountid)
* unique(relativeid, phone)
* */
@Entity
@Data
@Getter
@Setter
@ToString
@AllArgsConstructor
@NoArgsConstructor
public class DemiseRelative {

    @Id
    private UUID idRelative;

    @ManyToOne
    @Cascade(CascadeType.ALL)
    @JoinColumn(name = "demise_id", referencedColumnName = "idDemise")
    private DemiseEntity demises;

    private UUID DEMISEID;
    private UUID ACCOUNTID;
    private Kinship KINSHIP;
    private String PHONE; //? verificare utilizzo di demiserelative.phone in altre classi
    private String PHONEHASH;
    private String PREFIX;
}
