/*
 * This file is generated by jOOQ.
 */
package com.example.demodb.entityUpdate;


import com.example.demodb.entityUpdate.compositeKeys.KinshipTextKey;
import jakarta.persistence.Id;
import jakarta.persistence.IdClass;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;




//classe duplicata? è uguale a NotificationKinshipText
import jakarta.persistence.Entity;

import java.util.UUID;

@Entity
@Data
@AllArgsConstructor
@NoArgsConstructor

public class KinshipText {
    @Id
    private UUID id;
    private Kinship KINSHIP;

    private String TEXT;
}
