/*
 * This file is generated by jOOQ.
 */
package com.example.demodb.entityUpdate;


import javax.xml.catalog.Catalog;

public enum Lang {

    it_("it"),

    en("en");

    private final String literal;

    private Lang(String literal) {
        this.literal = literal;
    }

    /*
    @Override
    public Catalog getCatalog() {
        return getSchema().getCatalog();
    }


    @Override
    public String getName() {
        return "lang";
    }

    @Override
    public String getLiteral() {
        return literal;
    }*/
}
