/*
 * This file is generated by jOOQ.
 */
package com.example.demodb.entityUpdate;




import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;


import java.util.UUID;

@Entity
@Data
@AllArgsConstructor
@NoArgsConstructor
public class Telegram {

    @Id
    private UUID TELEGRAMID;

    private String NAME;
    private String SURNAME;
    private String EMAIL;
    private String RECEIVER;
    private String DEFUNCT;
    private String MESSAGE;

    private UUID USERID;
    private UUID DEMISEID;
    private Boolean APPROVEDPAY;
    private String PAYMENTID;
}
